### ISSUE TITLE
Implement automated regression testing

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-tools#124]
The CI/CD chain needs to be able to test a bitstream with all available unit tests.

For this a script is needed that can execute all those tests, record there results in log files, evaluate the combined result and report this back to the calling instance.

Parameters are a bitstream, a path to store the test logs and an optional device string to select the board to talk to.

## Todo
 - [ ] add field to regression test file that specifiers the platforms a test is intended for
   - [ ] need to remove hyperram test from platforms that don't have hyperram
 - [ ] update old tests to support proper unit test reporting
   - [ ] test_332: needs to set video mode to PAL to function properly

**Comment by lydon42** [comment]
This is related to #108

**Comment by lydon42** [comment]
test_332 does not video mode and coordinates are set for NTSC mode.

**Comment by lydon42** [comment]
Test 332 needs to properly switch to PAL mode on startup, as it is tuned (pixel wise) for that. It will fail if ran in NTSC mode.

**Comment by lydon42** [comment]
Bug: usbserial autodiscover needs to be able to match longer pnum sequences. Extend by one number, or make it arbitrary long?

**Comment by lydon42** [comment]
This works reasonably well, as the recent release test builds show. Now the infrastructure (jenkins, remote test hosts) and shell scripts (in core) have to be created.
